apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: aws-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs:
      - "*"
  - apiGroups:
      - provider.giantswarm.io
    resources:
      - awsconfigs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - aws-operator-secret
      - aws-operator-ssh-key-secret
      - aws-operator-pull-secret
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - aws-operator-configmap
    verbs:
      - get
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aws-operator
subjects:
  - kind: ServiceAccount
    name: aws-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: aws-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: aws-operator-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - aws-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aws-operator-psp
subjects:
  - kind: ServiceAccount
    name: aws-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: aws-operator-psp
  apiGroup: rbac.authorization.k8s.io
